"""missing"""
# Generated by Django 4.1.1 on 2022-10-07 20:30

from django.db import migrations


class Migration(migrations.Migration):
    """missing"""
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
