"""missing"""
# Generated by Django 4.1.1 on 2022-10-09 23:35

from django.db import migrations


class Migration(migrations.Migration):
    """missing"""
    dependencies = [
        ('blog', '0003_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
