"""missing"""
# Generated by Django 4.1.1 on 2022-10-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    """missing"""
    dependencies = [
        ('blog', '0011_comment_created_comment_post_comment_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(blank=True,\
                help_text='The date & time this comment was published', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='The date & time this article was published',\
                unique_for_date='published'),
        ),
    ]
