# Generated by Django 4.1.1 on 2022-11-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoContest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('banner', models.ImageField(blank=True, help_text='A banner image for the contest', null=True, upload_to='')),
                ('published', models.DateTimeField(blank=True, help_text='The date & time this sumbittion is made', null=True)),
            ],
        ),
    ]
